spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/world?serverTimezone=UTC&useSSL=true
        username: root
        password: admin
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
        cache-period: 0
    template:
        cache: false
mybatis:
  mapperLocations: classpath*:com/cone/**/dao/*.xml
#  typeAliasesPackage: com.cone.demo.model.bo
server:
  port: 8082
  contextPath: /hell #访问路径
#spring.mvc.view:
#  prefix: classpath:/static/
#  suffix: .html
########################################################
###THYMELEAF (ThymeleafAutoConfiguration)
########################################################
#spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
#    cache: false
#    cache-period: 0
#  template:
#    cache: false
logging:
  file: D:/mylog/log.log
  level:
    org.springframework.web: DEBUG
    root: INFO
other:
  name: 姓名 #可以通过@Value("${other.name}")注解在所有的bean中应用配置里面的属性
  code: HKJ9879JKL