spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test_oa?serverTimezone=UTC&useSSL=true
        username: root
        password: admin
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
security:
  user:
    name: admin
    password: admin
    role: USER
  ignored:
    /
    ,/demo/rest/dsds
mybatis:
  mapperLocations: classpath*:com/cone/**/dao/*.xml
#  typeAliasesPackage: com.cone.demo.model.bo
server:
  port: 8082
  contextPath: /hell
logging:
  file: D:/mylog/log.log
  level:
    org.springframework.web: DEBUG
    com.cone: DEBUG
    root: INFO
other:
  name: 姓名
  code: HKJ9879JKL